apiVersion: v1
kind: Service
metadata:
  name: cavs-www
  labels:
    app: cavs-www
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"cdn-backend-config"}}'
spec:
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app: cavs-www
  type: NodePort
