aliases:
- &dockerauth
  username: $$DOCKER_USERNAME
  password: "$$DOCKER_PASSWORD"
  email: $$DOCKER_EMAIL

- &volumes
  - "/root/.docker:/root/.docker"
  - "/root/.kube:/root/.kube"
  - "/var/run/docker.sock:/var/run/docker.sock"

cache:
  mount:
  - .git

build:
  build:
    image: eu.gcr.io/sanity-cloud/ci
    pull: true
    auth_config: *dockerauth
    volumes: *volumes
    commands:
    - docker build --pull -t eu.gcr.io/sanity-cloud/cavs-www:$$COMMIT .

  publish:
    image: eu.gcr.io/sanity-cloud/ci
    auth_config: *dockerauth
    volumes: *volumes
    commands:
    - docker tag eu.gcr.io/sanity-cloud/cavs-www:$$COMMIT eu.gcr.io/sanity-cloud/cavs-www:$$BRANCH
    - docker push eu.gcr.io/sanity-cloud/cavs-www:$$COMMIT
    - docker push eu.gcr.io/sanity-cloud/cavs-www:$$BRANCH
    when:
      event: push

  deploy:
    image: eu.gcr.io/sanity-cloud/ci
    auth_config: *dockerauth
    volumes: *volumes
    commands:
    - "sed -i -re 's/(image:[^:]+)($|:.+$)/\\1:$$COMMIT/g' kubernetes/production/deployment.yaml"
    - kubectl --context kubernetes01-eu-w1 --namespace clients apply -f kubernetes/production/
    when:
      branch: master
      event: push

  deploy-staging:
    image: eu.gcr.io/sanity-cloud/ci
    auth_config: *dockerauth
    volumes: *volumes
    commands:
    - "sed -i -re 's/(image:[^:]+)($|:.+$)/\\1:$$COMMIT/g' kubernetes/staging/deployment.yaml"
    - kubectl --context kubernetes01-eu-w1 --namespace clients-staging apply -f kubernetes/staging/
    when:
      branch: staging
      event: push

notify:
  email:
    from: $$SMTP_FROM
    host: $$SMTP_HOST
    port: $$SMTP_PORT
    username: $$SMTP_USERNAME
    password: $$SMTP_PASSWORD
    when:
      failure: true

  slack:
    webhook_url: $$SLACK_WEBHOOK
    username: $$SLACK_USERNAME
    channel: $$SLACK_CHANNEL
    template: "$$SLACK_TEMPLATE"
    when:
      failure: true
      change: true
