clone:
  clone:
    image: plugins/git
    depth: 1

pipeline:
  build:
    image: eu.gcr.io/sanity-cloud/ci
    pull: true
    secrets: [docker_auth, npmrc]
    commands:
    - ci-docker-build eu.gcr.io/sanity-cloud/cavs-www

  publish:
    image: eu.gcr.io/sanity-cloud/ci
    secrets: [docker_auth]
    commands:
    - ci-docker-push eu.gcr.io/sanity-cloud/cavs-www
    when:
      event: push

  deploy-production:
    image: eu.gcr.io/sanity-cloud/ci
    secrets: [kubernetes_auth, sentry_auth_token]
    commands:
    - ci-kubernetes-deploy eu.gcr.io/sanity-cloud/cavs-www clients kubernetes/production/
    #- ci-sentry-notify cavs-www production
    when:
      branch: master
      event: push

  deploy-staging:
    image: eu.gcr.io/sanity-cloud/ci
    secrets: [kubernetes_auth, sentry_auth_token]
    commands:
    - ci-kubernetes-deploy eu.gcr.io/sanity-cloud/cavs-www clients-staging kubernetes/staging/
    #- ci-sentry-notify cavs-www staging
    when:
      branch: staging
      event: push

  notify:
    image: eu.gcr.io/sanity-cloud/ci
    secrets: [postmark_server_token, slack_webhook]
    commands:
    - ci-notify
    when:
      status: [failure, success]
